import { writeFileSafe } from './utils.mjs';
import { SERVER_SCRIPT_PATH } from './constants.mjs';

export async function configureServer(host, log) {
  const script = `#!/bin/bash
# cmux-persistent-ssh — server optimization script
# run this on your remote server: bash ~/cmux-persist-server-setup.sh
# generated by: npx cmux-persistent-ssh
# safe to re-run — all operations are idempotent
set -euo pipefail

echo "=== 1/4: tuning sshd_config ==="
SSHD="/etc/ssh/sshd_config"
sudo sed -i.bak \\
  -e 's/^#TCPKeepAlive yes/TCPKeepAlive yes/' \\
  -e 's/^#ClientAliveInterval 0/ClientAliveInterval 60/' \\
  -e 's/^#ClientAliveCountMax 3/ClientAliveCountMax 120/' \\
  "$SSHD"
sudo rm -f "\${SSHD}.bak"
echo "  TCPKeepAlive=yes, ClientAliveInterval=60, ClientAliveCountMax=120"

# reload sshd (works on both macOS and linux)
if command -v launchctl &>/dev/null; then
  echo "  reloading sshd via launchctl..."
  sudo launchctl kickstart -k system/com.openssh.sshd 2>/dev/null || echo "  (may need manual restart)"
elif command -v systemctl &>/dev/null; then
  echo "  reloading sshd via systemctl..."
  sudo systemctl reload sshd 2>/dev/null || sudo systemctl restart sshd
fi

echo ""
echo "=== 2/4: patching ET launch daemon ==="
if command -v launchctl &>/dev/null; then
  # macOS
  PLIST="/Library/LaunchDaemons/homebrew.mxcl.et.plist"
  if [ -f "$PLIST" ]; then
    if ! grep -q "KeepAlive" "$PLIST"; then
      sudo /usr/libexec/PlistBuddy -c "Add :KeepAlive bool true" "$PLIST"
      echo "  added KeepAlive=true"
    else
      echo "  KeepAlive already set"
    fi
    echo "  restarting etserver..."
    sudo launchctl unload "$PLIST" 2>/dev/null || true
    sudo launchctl load -w "$PLIST"
  else
    echo "  ET plist not found at $PLIST, skipping"
  fi
elif command -v systemctl &>/dev/null; then
  # linux
  if systemctl list-unit-files | grep -q etserver; then
    sudo systemctl enable etserver
    sudo systemctl restart etserver
    echo "  enabled and restarted etserver via systemd"
  else
    echo "  etserver service not found, skipping"
  fi
fi

echo ""
echo "=== 3/4: power settings ==="
if command -v pmset &>/dev/null; then
  # macOS power management
  sudo pmset -a sleep 0
  sudo pmset -a powernap 0
  sudo pmset -a tcpkeepalive 1
  sudo pmset -a womp 1
  sudo pmset -a autorestart 1
  echo "  sleep=0, powernap=0, tcpkeepalive=1, womp=1, autorestart=1"
else
  echo "  not macOS, skipping pmset"
fi

echo ""
echo "=== 4/4: TCP keepalive sysctls ==="
if [[ "$(uname)" == "Darwin" ]]; then
  sudo sysctl -w net.inet.tcp.keepidle=600000
  sudo sysctl -w net.inet.tcp.keepintvl=30000
  sudo sysctl -w net.inet.tcp.keepcnt=15
  sudo sysctl -w net.inet.tcp.always_keepalive=1

  SYSCTL_CONF="/etc/sysctl.conf"
  sudo touch "$SYSCTL_CONF"
  for kv in "net.inet.tcp.keepidle=600000" "net.inet.tcp.keepintvl=30000" "net.inet.tcp.keepcnt=15" "net.inet.tcp.always_keepalive=1"; do
    key="\${kv%%=*}"
    if grep -q "$key" "$SYSCTL_CONF" 2>/dev/null; then
      sudo sed -i.bak "s|^\${key}=.*|\${kv}|" "$SYSCTL_CONF"
      sudo rm -f "\${SYSCTL_CONF}.bak"
    else
      echo "$kv" | sudo tee -a "$SYSCTL_CONF" > /dev/null
    fi
  done
  echo "  persisted to $SYSCTL_CONF"
else
  # linux
  sudo sysctl -w net.ipv4.tcp_keepalive_time=600
  sudo sysctl -w net.ipv4.tcp_keepalive_intvl=30
  sudo sysctl -w net.ipv4.tcp_keepalive_probes=15
  echo "net.ipv4.tcp_keepalive_time=600" | sudo tee -a /etc/sysctl.d/99-et-keepalive.conf > /dev/null
  echo "net.ipv4.tcp_keepalive_intvl=30" | sudo tee -a /etc/sysctl.d/99-et-keepalive.conf > /dev/null
  echo "net.ipv4.tcp_keepalive_probes=15" | sudo tee -a /etc/sysctl.d/99-et-keepalive.conf > /dev/null
  echo "  persisted to /etc/sysctl.d/99-et-keepalive.conf"
fi

echo ""
echo "=== all done ==="
echo "verify with:"
echo "  grep -E 'ClientAlive|TCPKeep' /etc/ssh/sshd_config"
if command -v pmset &>/dev/null; then
  echo "  pmset -g custom"
fi
if [[ "$(uname)" == "Darwin" ]]; then
  echo "  sysctl net.inet.tcp.keepidle net.inet.tcp.keepintvl net.inet.tcp.keepcnt"
else
  echo "  sysctl net.ipv4.tcp_keepalive_time net.ipv4.tcp_keepalive_intvl net.ipv4.tcp_keepalive_probes"
fi
`;

  await writeFileSafe(SERVER_SCRIPT_PATH, script);
  log(`wrote server script to ~/cmux-persist-server-setup.sh`);
  return SERVER_SCRIPT_PATH;
}
